spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nbaCollection
    username: root
    password: R25940151
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

crawl:
  team: false
  player: false
  match: true